# This is free and unencumbered software released into the public domain.

version: 2
updates:
  - package-ecosystem: docker
    directories:
      - adguardhome/**
      - caddy/**
      - gitea/**
      - ostree/**
    schedule:
      interval: daily
