# This is free and unencumbered software released into the public domain.

version: 2
updates:
  - package-ecosystem: docker
    directories:
      - adguardhome/**
      - caddy/**
      - fossflow/**
      - gitea/**
      - memos/**
      - ostree/**
      - penpot/**
      - postgres/**
      - starbase/**
      - valkey/**
      - vector/**
    schedule:
      interval: daily
