# This is free and unencumbered software released into the public domain.

FROM docker.io/caddy:latest@sha256:30ccf0cb027e1d06cd6e453c04fc1c8eec665629b22ed69602c14c8a0512ead0 AS build

RUN chmod ugo=rx /usr/bin/caddy

FROM scratch

COPY --from=build /usr/bin/caddy /usr/bin/caddy

EXPOSE 80

WORKDIR /opt/caddy

ENTRYPOINT ["/usr/bin/caddy"]

CMD [ \
	"run", \
	"--adapter", "caddyfile", \
	"--config", "/etc/caddy/caddyfile" \
]
