# This is free and unencumbered software released into the public domain.

FROM docker.io/alpine:latest@sha256:4bcff63911fcb4448bd4fdacec207030997caf25e9bea4045fa6c8c44de311d1 AS root

RUN apk add dos2unix

COPY ./ /tmp/git/

RUN rm -r /tmp/git/.git

RUN find /tmp/git -type f -print0 | xargs -0 dos2unix

FROM quay.io/fedora/fedora-coreos:stable@sha256:46020671ef1b209fc18d90e2151f7004022f3d3c1a4528eab69b36fe9f101fdf

# Copy entire repository into the '/tmp/git' folder.
COPY --from=root /tmp/git/ /tmp/git/

# Run the setup scripts.
RUN bash /tmp/git/ostree/src/setup.sh
