# This is free and unencumbered software released into the public domain.

FROM quay.io/fedora/fedora-coreos:stable@sha256:46020671ef1b209fc18d90e2151f7004022f3d3c1a4528eab69b36fe9f101fdf

SHELL ["/bin/bash", "-c"]

RUN --mount=target=/tmp/git for file in /tmp/git/ostree/src/*.sh; do bash "$file"; done && \
	rm --force --recursive /tmp/* && \
	ostree container commit
