# This is free and unencumbered software released into the public domain.

_default:
	just --list

build:
	docker build --file containerfile --tag ghcr.io/ngarside/gitea:latest .

run: stop
	docker run --detach --name gitea --publish 8080:3000 --read-only --volume {{ replace(justfile_directory(), '\', '/') }}/bin/opt:/opt/gitea --volume {{ replace(justfile_directory(), '\', '/') }}/bin/root:/root --volume {{ replace(justfile_directory(), '\', '/') }}/bin/tmp:/tmp ghcr.io/ngarside/gitea:latest

stop:
	docker stop gitea || true
