# This is free and unencumbered software released into the public domain.

# Type | Path             | Mode | User   | Group   | Age | Argument
  d      /var/home/nathan   0700   nathan   nathan    1d    -
