# This is free and unencumbered software released into the public domain.

# Type | Name   | ID | GECOS    | Home             | Shell
  u      nathan   -    "Nathan"   /var/home/nathan   /bin/bash

# Type | User   | Group
  m      nathan   wheel
