# This is free and unencumbered software released into the public domain.

FROM quay.io/fedora/fedora-coreos:stable

COPY ./sshd/authorizedkeys.conf /usr/etc/ssh/sshd_config.d/20-authorizedkeys.conf
COPY ./sshd/hardening.conf /usr/etc/ssh/sshd_config.d/10-hardening.conf
COPY ./sshd/authorizedkeys.txt /usr/etc/ssh/authorized_keys/core

COPY ./adguardhome/adguardhome.service /usr/lib/systemd/system/adguardhome.service

COPY ./ostree/setup.sh /tmp/setup

COPY ./ostree/vconsole.conf /usr/etc/vconsole.conf

COPY ./ostree/sysctl.conf /usr/etc/sysctl.d/0-server.conf

RUN chmod +x /tmp/setup && /tmp/setup && rm --force /tmp/setup
