# This is free and unencumbered software released into the public domain.

FROM quay.io/fedora/fedora-coreos:stable

COPY ./ostree/authorizedkeys.txt /var/home/core/.ssh/authorized_keys.d/ostree

COPY ./sshd/authorizedkeys.conf /usr/etc/ssh/sshd_config.d/20-authorizedkeys.conf
COPY ./sshd/hardening.conf /usr/etc/ssh/sshd_config.d/10-hardening.conf

COPY ./adguardhome/adguardhome.service /usr/lib/systemd/system/adguardhome.service

COPY ./ostree/setup.sh /tmp/setup

RUN chmod +x /tmp/setup && /tmp/setup && rm --force /tmp/setup
