# This is free and unencumbered software released into the public domain.

FROM quay.io/fedora/fedora-coreos:stable@sha256:9a71369f35a8d72ffc7dae2d5ff78159587e4d278127728c269582a4df8c4c28

COPY ./sshd/authorizedkeys.conf /usr/etc/ssh/sshd_config.d/20-authorizedkeys.conf
COPY ./sshd/hardening.conf /usr/etc/ssh/sshd_config.d/10-hardening.conf
COPY ./sshd/authorizedkeys.txt /usr/etc/ssh/authorized_keys/core

COPY ./adguardhome/ops/filesystem.service /usr/lib/systemd/system/adguardhome-filesystem.service
COPY ./adguardhome/ops/pull.service /usr/lib/systemd/system/adguardhome-pull.service
COPY ./adguardhome/ops/resolved.service /usr/lib/systemd/system/adguardhome-resolved.service
COPY ./adguardhome/ops/run.service /usr/lib/systemd/system/adguardhome-run.service

COPY ./caddy/ops/caddyfile /etc/caddy/caddyfile
COPY ./caddy/ops/caddy.service /usr/lib/systemd/system/caddy.service

COPY ./ostree/setup.sh /tmp/setup

COPY ./ostree/vconsole.conf /usr/etc/vconsole.conf

COPY ./ostree/sysctl.conf /usr/etc/sysctl.d/0-server.conf

COPY ./ostree/subuid.txt /usr/etc/subuid

RUN chmod +x /tmp/setup && /tmp/setup && rm --force /tmp/setup
