# This is free and unencumbered software released into the public domain.

FROM quay.io/fedora/fedora-coreos:stable@sha256:46020671ef1b209fc18d90e2151f7004022f3d3c1a4528eab69b36fe9f101fdf

COPY ./sshd/authorizedkeys.conf /usr/etc/ssh/sshd_config.d/20-authorizedkeys.conf
COPY ./sshd/hardening.conf /usr/etc/ssh/sshd_config.d/10-hardening.conf
COPY ./sshd/authorizedkeys.txt /usr/etc/ssh/authorized_keys/core

COPY ./adguardhome/ops/stub.conf /usr/etc/systemd/resolved.conf.d/stub.conf
COPY ./adguardhome/ops/filesystem.service /usr/lib/systemd/system/adguardhome-filesystem.service
COPY ./adguardhome/ops/pull.service /usr/lib/systemd/system/adguardhome-pull.service
COPY ./adguardhome/ops/resolved.service /usr/lib/systemd/system/adguardhome-resolved.service
COPY ./adguardhome/ops/run.service /usr/lib/systemd/system/adguardhome-run.service

COPY ./caddy/ops/caddyfile /etc/caddy/caddyfile

COPY ./ostree/setup.sh /tmp/setup

COPY ./ostree/vconsole.conf /usr/etc/vconsole.conf

COPY ./ostree/sysctl.conf /usr/etc/sysctl.d/0-server.conf

COPY ./ostree/subuid.txt /usr/etc/subuid

COPY ./ostree/policy.json /usr/etc/containers/policy.json

COPY ./restic/src/restic.env /usr/etc/restic/restic.env
COPY ./restic/src/restic.sh /usr/etc/restic/restic.sh
COPY ./restic/ops/restic.service /usr/lib/systemd/system/restic.service
COPY ./restic/ops/restic.timer /usr/lib/systemd/system/restic.timer

COPY ./caddy/ops/caddy.container /usr/etc/containers/systemd/users/1001/caddy.container
COPY ./caddy/ops/internal.network /usr/etc/containers/systemd/users/1001/internal.network

RUN chmod +x /tmp/setup && /tmp/setup && rm --force /tmp/setup
