# This is free and unencumbered software released into the public domain.

[customizations.installer.kickstart]
contents = """
	autopart --noswap --type=lvm
	clearpart --all --drives=vda --initlabel
	ignoredisk --only-use=vda
	rootpw --lock
	text --non-interactive
	zerombr
"""
