# This is free and unencumbered software released into the public domain.

[customizations.installer.kickstart]
contents = """
	autopart --noswap --type=btrfs --nohome
	clearpart --all --drives=nvme0,vda --initlabel
	ignoredisk --only-use=nvme0,vda
	reboot --eject
	rootpw --lock
	text --non-interactive
	zerombr
"""
