# This is free and unencumbered software released into the public domain.

[api]
address = "0.0.0.0:8686"
enabled = true

[sources.vector_metrics]
type = "internal_metrics"

[sinks.vector_prometheus]
auth.password = "$GRAFANA_PROMETHEUS_PASSWORD"
auth.strategy = "basic"
auth.user = "$GRAFANA_PROMETHEUS_USERNAME"
endpoint = "$GRAFANA_PROMETHEUS_URI"
inputs = ["vector_metrics"]
type = "prometheus_remote_write"
