# This is free and unencumbered software released into the public domain.

name: adguardhome

on:
  push:
    branches:
      - master
  schedule:
    - cron: 0 0 * * 1
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: build
        run: podman build --file adguardhome.containerfile --tag ghcr.io/ngarside/adguardhome:latest .
        working-directory: adguardhome

      - name: save
        run: podman save --output adguardhome.tar ghcr.io/ngarside/adguardhome:latest

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          compression-level: 9
          name: adguardhome
          path: adguardhome.tar
          retention-days: 1

  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:

      - name: download
        uses: actions/download-artifact@v4
        with:
          name: adguardhome
          path: adguardhome.tar

      - name: load
        run: podman load --input adguardhome.tar

      - name: login
        run: podman login ghcr.io --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}

      - name: push
        run: podman push ghcr.io/ngarside/adguardhome:latest
