# This is free and unencumbered software released into the public domain.

name: adguardhome

on:
  pull_request:
    paths: ['**/adguardhome.yml', 'adguardhome/src/**', 'requirements.txt', 'scripts/**']
  push:
    branches: [master]
    paths: ['**/adguardhome.yml', 'adguardhome/src/**', 'scripts/**']
  workflow_dispatch:

jobs:
  container_build:
    uses: ./.github/workflows/container_build.yml
    permissions: {contents: read, packages: write}
    with:
      name: adguardhome
      path: adguardhome/src/adguardhome.dockerfile
