# This is free and unencumbered software released into the public domain.

name: adguardhome
on:
  pull_request:
    paths:
      - '**/adguardhome/**'
      - scripts/**
  push:
    branches:
      - master
    paths:
      - '**/adguardhome/**'
      - scripts/**
  schedule:
    - cron: 0 0 * * 1
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: pipenv
        run: pip install pipenv && pipenv install

      - name: tag
        run: echo "TAG=$(pipenv run python3 scripts/src/tag_branch.py)" >> $GITHUB_ENV

      - name: build
        run: podman build --file adguardhome/src/adguardhome.dockerfile --tag ghcr.io/ngarside/adguardhome:$TAG .

      - name: test
        run: pipenv run pytest adguardhome

      - name: login
        run: podman login ghcr.io --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}

      - name: push
        run: podman push ghcr.io/ngarside/adguardhome:$TAG
