# This is free and unencumbered software released into the public domain.

name: adguardhome

on:
  pull_request:
    paths: ['**adguardhome**', 'scripts/**']
  push:
    branches: [master]
    paths: ['**adguardhome**', 'scripts/**']
  schedule: [cron: 0 0 * * 1]
  workflow_dispatch:

jobs:
  build:
    uses: container_build.yml
    with:
      name: adguardhome
      path: adguardhome/src/adguardhome.dockerfile
