# This is free and unencumbered software released into the public domain.

name: adguardhome

on:
  pull_request:
    paths:
      - .github/workflows/adguardhome.yml
      - adguardhome/**
      - scripts/**
  push:
    branches:
      - master
    paths:
      - .github/workflows/adguardhome.yml
      - adguardhome/**
      - scripts/**
  schedule:
    - cron: 0 0 * * 1
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: pipenv
        run: pip install pipenv && pipenv install

      - name: tag
        run: echo "TAG=$(pipenv run python3 scripts/src/tag_branch.py)" >> $GITHUB_ENV

      - name: build
        run: podman build --file src/adguardhome.dockerfile --tag ghcr.io/ngarside/adguardhome:$TAG .
        working-directory: adguardhome

      - name: test
        run: pipenv run pytest
        working-directory: adguardhome

      - name: save
        run: podman save --output adguardhome.tar ghcr.io/ngarside/adguardhome:$TAG

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          compression-level: 9
          name: adguardhome
          path: adguardhome.tar
          retention-days: 1

  publish:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:

      - name: download
        uses: actions/download-artifact@v4
        with:
          name: adguardhome

      - name: load
        run: podman load --input adguardhome.tar

      - name: login
        run: podman login ghcr.io --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}

      - name: push
        run: podman push ghcr.io/ngarside/adguardhome
