# This is free and unencumbered software released into the public domain.

name: authentik

on:
  pull_request:
    paths: ['**/authentik.yaml', 'authentik/[st]*/**', 'pyproject.toml', 'scripts/**']
  push:
    branches: [master]
    paths: ['**/authentik.yaml', 'authentik/src/**']
  workflow_dispatch:

jobs:
  container_build:
    uses: ./.github/workflows/container_build.yaml
    permissions: {contents: read, packages: write}
    with: { path: authentik/src/authentik.dockerfile }
