# This is free and unencumbered software released into the public domain.

name: caddy

on:
  pull_request:
    paths: ['**/caddy.yml', 'caddy/src/**', 'pyproject.toml', 'scripts/**']
  push:
    branches: [master]
    paths: ['**/caddy.yml', 'caddy/src/**', 'scripts/**']
  workflow_dispatch:

jobs:
  container_build:
    uses: ./.github/workflows/container_build.yml
    permissions: {contents: read, packages: write}
    with:
      name: caddy
      path: caddy/src/caddy.dockerfile
