# This is free and unencumbered software released into the public domain.

name: caddy

on:
  pull_request:
    paths:
      caddy
  push:
    branches:
      - master
    paths:
      caddy
  schedule:
    - cron: 0 0 * * 1
  workflow_dispatch:

jobs:
  caddy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: login
        run: podman login ghcr.io --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}

      - name: build
        run: podman build --file containerfile --tag ghcr.io/ngarside/caddy:latest .
        working-directory: caddy

      - name: push
        run: podman push ghcr.io/ngarside/caddy:latest
