# This is free and unencumbered software released into the public domain.

name: fossflow

on:
  pull_request:
    paths: ['**/fossflow.yml', 'fossflow/src/**', 'pyproject.toml', 'scripts/**']
  push:
    branches: [master]
    paths: ['**/fossflow.yml', 'fossflow/src/**']
  workflow_dispatch:

jobs:
  container_build:
    uses: ./.github/workflows/container_build.yml
    permissions: {contents: read, packages: write}
    with:
      name: fossflow
      path: fossflow/src/fossflow.dockerfile
