# This is free and unencumbered software released into the public domain.

name: gitea

on:
  pull_request:
    paths: ['**/gitea.yml', 'gitea/[st]*/**', 'pyproject.toml', 'scripts/**']
  push:
    branches: [master]
    paths: ['**/gitea.yml', 'gitea/src/**']
  workflow_dispatch:

jobs:
  container_build:
    uses: ./.github/workflows/container_build.yml
    permissions: {contents: read, packages: write}
    with:
      name: gitea
      path: gitea/src/gitea.dockerfile
