# This is free and unencumbered software released into the public domain.

name: iso

on:
  pull_request:
    paths:
      - .github/workflows/iso.yml
      - iso/**
  push:
    branches:
      - master
    paths:
      - .github/workflows/iso.yml
      - iso/**
  schedule:
    - cron: 0 0 * * 1
  workflow_dispatch:

jobs:
  iso:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: build
        run: bash build.sh
        working-directory: iso

      # https://stackoverflow.com/a/69977763
      - name: change ownership
        run: |
          USER=$(whoami)
          sudo chown $USER:$USER iso/bin/server.iso

      - name: package
        if: github.ref_name == 'master'
        uses: actions/upload-artifact@v4
        with:
          name: server.iso
          path: iso/bin/server.iso
          retention-days: 7
