# This is free and unencumbered software released into the public domain.

name: iso

on:
  pull_request:
    paths: ['**iso**', 'scripts/**']
  push:
    branches: [master]
    paths: ['**iso**']
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v5

      - name: Build ISO
        run: bash src/build.sh
        working-directory: iso

      # https://stackoverflow.com/a/69977763
      - name: Change ownership
        run: |
          USER=$(whoami)
          sudo chown $USER:$USER iso/bin/server.iso

      - name: Package
        uses: actions/upload-artifact@v4
        with:
          name: server.iso
          path: iso/bin/server.iso
          retention-days: 7
