# This is free and unencumbered software released into the public domain.

name: iso

on:
  push:
  schedule:
    - cron: 0 0 * * 1
  workflow_dispatch:

jobs:
  iso:
    runs-on: ubuntu-latest
    steps:

      - name: build
        run: ./build.sh
        working-directory: iso

      - name: package
        uses: actions/upload-artifact@v4
        with:
          name: server.iso
          path: iso/bin/server.iso
