# This is free and unencumbered software released into the public domain.

name: lint

on:
  pull_request:
  workflow_dispatch:

jobs:
  ruff:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: install
        run: pip install pipenv && pipenv install

      - name: check
        run: pipenv run ruff check

  shellcheck:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: check
        run: git ls-files | grep '\.sh$' | xargs shellcheck

  yamllint:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: check
        run: yamllint .
