# This is free and unencumbered software released into the public domain.

name: bootc

on:
  pull_request:
    paths: ['**/ops/**', '**bootc**', 'pyproject.toml', 'scripts/**']
  push:
    branches: [master]
    paths: ['**/ops/**', '**bootc**']
  workflow_dispatch:

jobs:
  container_build:
    uses: ./.github/workflows/container_build.yml
    permissions: {contents: read, packages: write}
    with:
      name: server
      path: bootc/src/bootc.dockerfile
