# This is free and unencumbered software released into the public domain.

name: ostree

on:
  pull_request:
    paths: ['**/ops/**', '**ostree**', 'pyproject.toml', 'scripts/**']
  push:
    branches: [master]
    paths: ['**/ops/**', '**ostree**']
  workflow_dispatch:

jobs:
  container_build:
    uses: ./.github/workflows/container_build.yml
    permissions: {contents: read, packages: write}
    with:
      name: server
      path: ostree/src/ostree.dockerfile
