# This is free and unencumbered software released into the public domain.

name: ostree

on:
  pull_request:
    paths:
      - .github/workflows/ostree.yml
      - ostree/**
      - scripts/**
  push:
    branches:
      - master
    paths:
      - .github/workflows/ostree.yml
      - ostree/**
      - scripts/**
  schedule:
    - cron: 0 0 * * 1
  workflow_dispatch:

jobs:
  ostree:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: login
        run: podman login ghcr.io --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}

      - name: build
        run: podman build --file ostree/dockerfile --tag ghcr.io/ngarside/server:latest .

      - name: push
        run: podman push ghcr.io/ngarside/server:latest

      - name: purge
        uses: actions/delete-package-versions@v5
        with:
          package-name: server
          package-type: container
          delete-only-untagged-versions: true
