# This is free and unencumbered software released into the public domain.

name: penpot-frontend

on:
  pull_request:
    paths: ['**/penpot_frontend.yml', 'penpot/src/**', 'pyproject.toml', 'scripts/**']
  push:
    branches: [master]
    paths: ['**/penpot_frontend.yml', 'penpot/src/**']
  workflow_dispatch:

jobs:
  container_build:
    uses: ./.github/workflows/container_build.yml
    permissions: {contents: read, packages: write}
    with:
      name: penpot-frontend
      path: penpot/src/frontend.dockerfile
