# This is free and unencumbered software released into the public domain.

name: penpot-backend

on:
  pull_request:
    paths:
      - .github/workflows/penpot-backend.yml
      - penpot/**
      - scripts/**
  push:
    branches:
      - master
    paths:
      - .github/workflows/penpot-backend.yml
      - penpot/**
      - scripts/**
  schedule:
    - cron: 0 0 * * 1
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: build
        run: podman build --file src/backend.dockerfile --tag ghcr.io/ngarside/penpot-backend:latest .
        working-directory: penpot

      - name: save
        run: podman save --output penpot-backend.tar ghcr.io/ngarside/penpot-backend:latest

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          compression-level: 9
          name: penpot-backend
          path: penpot-backend.tar
          retention-days: 1

  publish:
    if: github.ref_name == 'master'
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:

      - name: download
        uses: actions/download-artifact@v4
        with:
          name: penpot-backend

      - name: load
        run: podman load --input penpot-backend.tar

      - name: login
        run: podman login ghcr.io --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}

      - name: push
        run: podman push ghcr.io/ngarside/penpot-backend:latest

      - name: purge
        uses: actions/delete-package-versions@v5
        with:
          package-name: penpot-backend
          package-type: container
          delete-only-untagged-versions: true
