# This is free and unencumbered software released into the public domain.

name: postgres

on:
  pull_request:
    paths: ['**postgres**', 'scripts/**']
  push:
    branches: [master]
    paths: ['**postgres**', 'scripts/**']
  schedule: [cron: 0 0 * * 1]
  workflow_dispatch:

jobs:
  container_build:
    uses: ./.github/workflows/container_build.yml
    permissions: {contents: read, packages: write}
    with:
      name: postgres
      path: postgres/src/postgres.dockerfile
