# This is free and unencumbered software released into the public domain.

name: postgres

on:
  pull_request:
    paths:
      - .github/workflows/postgres.yml
      - postgres/**
      - scripts/**
  push:
    branches:
      - master
    paths:
      - .github/workflows/postgres.yml
      - postgres/**
      - scripts/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: pipenv
        run: pip install pipenv && pipenv install

      - name: tag
        run: echo "TAG=$(pipenv run python3 scripts/tag_branch.py)" >> $GITHUB_ENV

      - name: build
        run: podman build --file src/postgres.dockerfile --tag ghcr.io/ngarside/postgres:$TAG .
        working-directory: postgres

      - name: test
        run: pipenv run pytest
        working-directory: postgres

      - name: save
        run: podman save --output postgres.tar ghcr.io/ngarside/postgres:$TAG

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          compression-level: 9
          name: postgres
          path: postgres.tar
          retention-days: 1

  publish:
    if: github.ref_name == 'master'
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:

      - name: download
        uses: actions/download-artifact@v4
        with:
          name: postgres

      - name: load
        run: podman load --input postgres.tar

      - name: login
        run: podman login ghcr.io --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}

      - name: push
        run: podman push ghcr.io/ngarside/postgres

      - name: purge
        uses: actions/delete-package-versions@v5
        with:
          package-name: postgres
          package-type: container
          delete-only-untagged-versions: true
