# This is free and unencumbered software released into the public domain.

name: pullrequest

on:
  pull_request:
  workflow_dispatch:

jobs:
  pullrequest:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: shellcheck
        run: shellcheck **/*.sh

  ruff:
    runs-on: ubuntu-latest
    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: install
        run: pip install pipenv && pipenv install

      - name: check
        run: pipenv run ruff check
