# This is free and unencumbered software released into the public domain.

name: restic

on:
  pull_request:
    paths: ['**/restic.yml']
  schedule:
    - cron: 0 0 * * 0
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v5

      - name: Clean
        run: >
          podman run
          --env AWS_ACCESS_KEY_ID --env AWS_SECRET_ACCESS_KEY
          --env RESTIC_PASSWORD --env RESTIC_REPOSITORY
          ghcr.io/restic/restic forget --keep-last 100 --prune
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.RESTIC_REPOSITORY_KEY }}
          RESTIC_PASSWORD: ${{ secrets.RESTIC_REPOSITORY_PASSWORD }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.RESTIC_REPOSITORY_SECRET }}
          RESTIC_REPOSITORY: ${{ secrets.RESTIC_REPOSITORY_URI }}
