# This is free and unencumbered software released into the public domain.

name: valkey

on:
  pull_request:
    paths:
      - .github/workflows/valkey.yml
      - valkey/**
      - scripts/**
  push:
    branches:
      - master
    paths:
      - .github/workflows/valkey.yml
      - valkey/**
      - scripts/**
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:

      - name: checkout
        uses: actions/checkout@v4

      - name: pipenv
        run: pip install pipenv && pipenv install

      - name: build
        run: podman build --file src/valkey.dockerfile --tag ghcr.io/ngarside/valkey:latest .
        working-directory: valkey

      - name: test
        run: pipenv run pytest
        working-directory: valkey

      - name: save
        run: podman save --output valkey.tar ghcr.io/ngarside/valkey:latest

      - name: upload
        uses: actions/upload-artifact@v4
        with:
          compression-level: 9
          name: valkey
          path: valkey.tar
          retention-days: 1

  publish:
    if: github.ref_name == 'master'
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:

      - name: download
        uses: actions/download-artifact@v4
        with:
          name: valkey

      - name: load
        run: podman load --input valkey.tar

      - name: login
        run: podman login ghcr.io --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }}

      - name: push
        run: podman push ghcr.io/ngarside/valkey

      - name: purge
        uses: actions/delete-package-versions@v5
        with:
          package-name: valkey
          package-type: container
          delete-only-untagged-versions: true
