# This is free and unencumbered software released into the public domain.

name: valkey

on:
  pull_request:
    paths: ['**/valkey.yaml', 'valkey/[st]*/**', 'pyproject.toml', 'scripts/**']
  push:
    branches: [master]
    paths: ['valkey/src/**']
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    permissions: { contents: read, packages: write }
    with: { path: valkey/src/valkey.dockerfile }
