# This is free and unencumbered software released into the public domain.

name: valkey

on:
  pull_request:
    paths: ['**valkey**', 'scripts/**', 'requirements.txt']
  push:
    branches: [master]
    paths: ['**valkey**', 'scripts/**', 'requirements.txt']
  schedule: [cron: 0 0 * * 1]
  workflow_dispatch:

jobs:
  container_build:
    uses: ./.github/workflows/container_build.yml
    permissions: {contents: read, packages: write}
    with:
      name: valkey
      path: valkey/src/valkey.dockerfile
