# This is free and unencumbered software released into the public domain.

name: valkey

on:
  pull_request:
    paths: ['**/valkey.yaml', 'valkey/[st]*/**', 'pyproject.toml', 'scripts/**']
  push:
    branches: [master]
    paths: ['**/valkey.yaml', 'valkey/src/**']
  workflow_dispatch:

jobs:
  container_build:
    uses: ./.github/workflows/container_build.yaml
    permissions: {contents: read, packages: write}
    with: { path: valkey/src/valkey.dockerfile }
