# This is free and unencumbered software released into the public domain.

name: victoriametrics

on:
  pull_request:
    paths: ['**/victoriametrics.yaml', 'victoriametrics/[st]*/**', 'pyproject.toml', 'scripts/**']
  push:
    branches: [master]
    paths: ['victoriametrics/src/**']
  workflow_dispatch:

jobs:
  build:
    uses: ./.github/workflows/build.yaml
    permissions: { contents: read, packages: write }
    with: { path: victoriametrics/src/victoriametrics.dockerfile }
